language: objective-c
osx_image: xcode7.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - bundle install
  - bundle exec pod keys set mailgun_api $MailgunApiKey
  - bundle exec pod keys set from_email $FromEmailAddress
  - bundle exec pod install
install: true
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace SendToMe.xcworkspace -scheme "SendToMe" -destination "OS=9.2,name=iPhone 6s Plus" test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
